### PR TITLE
Build with --release flag instead of --no-debug

### PR DESCRIPTION
**Pull request by Sija**
As per https://github.com/crystal-lang/shards/pull/126#issuecomment-380790538

### CODE REVIEW

**Comment by hugoabonizio** [comment]
`--release` flag was removed in https://github.com/veelenga/ameba/commit/c5729b1e9b2f4de1e8f789dd77887f5fc6f29959#diff-b67911656ef5d18c4ae36cb6741b7965 (see #31)

The combination of `--release --no-debug` flags was required to avoid a compilation bug on Ubuntu (see crystal-lang/crystal#4719).

I think just removing `--no-debug` flag is fine.

**Comment by veelenga** [comment]
Is `--no-debug` still needed for lastest Crystal? I believe not as Travis passes now.

**Comment by Sija** [comment]
Done in #48.

**Comment by hugoabonizio** [comment]
@veelenga IIRC this was fixed in version `0.24.1`. It's not needed anymore at least on my Ubuntu 16.04 machine.

**Pull request closed without merging**
